#!/usr/bin/env bash
# =============================================================================
# GitHub Actions Supply Chain Attack — Compromise Checker
# Generated by github-actions-supply-chain-response skill
#
# Usage:
#   ./check_gha_compromise.sh <org_name> <action_name> [--dry-run]
#
# This script checks whether a compromised GitHub Action is referenced in your
# organization's workflows, hunts for indicators of compromise in workflow run
# logs, and offers guided remediation with confirmation prompts before any
# destructive action.
#
# Customize the variables in the CONFIGURATION section below for your specific
# incident before running.
# =============================================================================

set -euo pipefail

# --------------- CONFIGURATION — EDIT THESE FOR YOUR INCIDENT ----------------

# Compromised action (owner/name)
COMPROMISED_ACTION="${COMPROMISED_ACTION:-__ACTION__}"

# Attack window (UTC, ISO 8601)
ATTACK_WINDOW_START="${ATTACK_WINDOW_START:-__START__}"
ATTACK_WINDOW_END="${ATTACK_WINDOW_END:-__END__}"

# Known C2 domains (space-separated, for log searching)
C2_DOMAINS="${C2_DOMAINS:-__C2_DOMAINS__}"

# Known safe commit SHA to pin to
SAFE_SHA="${SAFE_SHA:-__SAFE_SHA__}"

# ----------------------------- END CONFIGURATION -----------------------------

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color
BOLD='\033[1m'

# Globals
ORG="${1:-}"
ACTION="${2:-}"
DRY_RUN=false
FINDINGS=()
ACTIONS_TAKEN=()

for arg in "$@"; do
    if [[ "$arg" == "--dry-run" ]]; then
        DRY_RUN=true
    fi
done

# ----------------------------- UTILITY FUNCTIONS -----------------------------

print_header() {
    echo ""
    echo -e "${BOLD}${BLUE}═══════════════════════════════════════════════════════════${NC}"
    echo -e "${BOLD}${BLUE}  $1${NC}"
    echo -e "${BOLD}${BLUE}═══════════════════════════════════════════════════════════${NC}"
    echo ""
}

print_phase() {
    echo ""
    echo -e "${BOLD}── Phase $1: $2 ──${NC}"
    echo ""
}

ok()      { echo -e "  ${GREEN}[OK]${NC} $1"; }
finding() { echo -e "  ${RED}[!!]${NC} $1"; FINDINGS+=("$1"); }
warn()    { echo -e "  ${YELLOW}[??]${NC} $1"; }
info()    { echo -e "  ${BLUE}[--]${NC} $1"; }

confirm_action() {
    local description="$1"
    local command="$2"

    if $DRY_RUN; then
        info "DRY RUN — would execute: $command"
        return 1
    fi

    echo ""
    echo -e "  ${YELLOW}Action:${NC} $description"
    echo -e "  ${YELLOW}Command:${NC} $command"
    read -r -p "  Proceed? [y/N] " response
    case "$response" in
        [yY][eE][sS]|[yY])
            eval "$command"
            ACTIONS_TAKEN+=("$description")
            return 0
            ;;
        *)
            info "Skipped."
            return 1
            ;;
    esac
}

check_command() {
    command -v "$1" >/dev/null 2>&1
}

# ----------------------------- VALIDATION ------------------------------------

if [[ -z "$ORG" ]] || [[ "$ORG" == "--dry-run" ]]; then
    echo "Usage: $0 <org_name> <action_name> [--dry-run]"
    echo ""
    echo "Example: $0 myorg aquasecurity/trivy-action"
    echo "         $0 myorg aquasecurity/trivy-action --dry-run"
    exit 1
fi

if [[ -z "$ACTION" ]] || [[ "$ACTION" == "--dry-run" ]]; then
    if [[ "$COMPROMISED_ACTION" == "__ACTION__" ]]; then
        echo "Error: action_name argument required, or set COMPROMISED_ACTION env var"
        exit 1
    fi
    ACTION="$COMPROMISED_ACTION"
fi

# Override config if action was passed as argument
if [[ "$COMPROMISED_ACTION" == "__ACTION__" ]]; then
    COMPROMISED_ACTION="$ACTION"
fi

if ! check_command gh; then
    echo "Error: gh CLI is required but not found. Install from https://cli.github.com/"
    exit 1
fi

print_header "GitHub Actions Supply Chain Attack Checker"
info "Organization:     $ORG"
info "Action:           $COMPROMISED_ACTION"
info "Attack window:    $ATTACK_WINDOW_START .. $ATTACK_WINDOW_END"
info "C2 domains:       $C2_DOMAINS"
info "Safe SHA:         $SAFE_SHA"
info "Dry run:          $DRY_RUN"
echo ""

# ======================== PHASE 1: EXPOSURE CHECK ============================

print_phase "1" "Exposure Check"

# 1a. Search across the org for references to the action
info "Searching for $COMPROMISED_ACTION across $ORG..."
SEARCH_RESULTS=""
if SEARCH_RESULTS=$(gh search code "uses: $COMPROMISED_ACTION" --owner "$ORG" --json repository,path 2>/dev/null); then
    REPO_COUNT=$(echo "$SEARCH_RESULTS" | jq -r 'length' 2>/dev/null || echo "0")
    if [[ "$REPO_COUNT" -gt 0 ]]; then
        finding "Found $REPO_COUNT workflow references to $COMPROMISED_ACTION"
        echo "$SEARCH_RESULTS" | jq -r '.[] | "    \(.repository.nameWithOwner) — \(.path)"' 2>/dev/null || true
    else
        ok "No references to $COMPROMISED_ACTION found across $ORG"
    fi
else
    warn "gh search failed — you may need to search manually or check authentication"
fi

# 1b. Check local workflows if we're in a git repo
if [[ -d ".github/workflows" ]]; then
    info "Checking local .github/workflows/ for references..."
    LOCAL_REFS=$(grep -rn "$COMPROMISED_ACTION" .github/workflows/ 2>/dev/null || true)
    if [[ -n "$LOCAL_REFS" ]]; then
        finding "Local workflow references found:"
        echo "$LOCAL_REFS" | sed 's/^/    /'

        # 1c. Check tag-based vs SHA-pinned
        TAG_REFS=$(echo "$LOCAL_REFS" | grep -E "@v[0-9]|@main|@master" || true)
        SHA_REFS=$(echo "$LOCAL_REFS" | grep -E "@[a-f0-9]{40}" || true)

        if [[ -n "$TAG_REFS" ]]; then
            finding "TAG-BASED references (VULNERABLE to tag overwriting):"
            echo "$TAG_REFS" | sed 's/^/    /'
        fi
        if [[ -n "$SHA_REFS" ]]; then
            warn "SHA-pinned references found (verify SHAs are not malicious commits):"
            echo "$SHA_REFS" | sed 's/^/    /'
        fi
    else
        ok "No local workflow references to $COMPROMISED_ACTION"
    fi
else
    info "No .github/workflows/ directory — skipping local check"
fi

# ======================== PHASE 2: RUN WINDOW CONFIRMATION ===================

print_phase "2" "Run Window Confirmation"

if [[ "$ATTACK_WINDOW_START" == "__START__" ]] || [[ "$ATTACK_WINDOW_END" == "__END__" ]]; then
    warn "Attack window not configured — skipping run window check"
    warn "Set ATTACK_WINDOW_START and ATTACK_WINDOW_END to enable this phase"
else
    # Get list of repos that reference the action
    AFFECTED_REPOS=""
    if [[ -n "$SEARCH_RESULTS" ]] && [[ "$REPO_COUNT" -gt 0 ]]; then
        AFFECTED_REPOS=$(echo "$SEARCH_RESULTS" | jq -r '.[].repository.nameWithOwner' 2>/dev/null | sort -u)
    fi

    if [[ -n "$AFFECTED_REPOS" ]]; then
        info "Checking workflow runs during attack window..."
        while IFS= read -r repo; do
            info "Repository: $repo"
            RUNS=$(gh api "/repos/$repo/actions/runs?per_page=100&created=${ATTACK_WINDOW_START}..${ATTACK_WINDOW_END}" \
                --jq '.workflow_runs[] | "\(.id)|\(.created_at)|\(.conclusion)|\(.name)"' 2>/dev/null || true)
            if [[ -n "$RUNS" ]]; then
                finding "Workflow runs during attack window in $repo:"
                echo "$RUNS" | while IFS='|' read -r run_id created conclusion name; do
                    echo -e "    Run $run_id | $created | $conclusion | $name"
                done
            else
                ok "No runs during attack window in $repo"
            fi
        done <<< "$AFFECTED_REPOS"
    else
        info "No affected repos identified — skipping run window check"
    fi
fi

# ======================== PHASE 3: IOC HUNTING ===============================

print_phase "3" "IOC Hunting"

# 3a. Check for exfiltration dead drop repos
info "Checking for exfiltration dead drop repositories..."
DEAD_DROPS=$(gh api "/orgs/$ORG/repos" --paginate --jq '.[] | select(.name | test("tpcp|docs-tpcp"; "i")) | .full_name' 2>/dev/null || true)
if [[ -n "$DEAD_DROPS" ]]; then
    finding "Exfiltration dead drop repos found:"
    echo "$DEAD_DROPS" | sed 's/^/    /'
else
    ok "No known dead drop repos (tpcp, docs-tpcp) found in $ORG"
fi

# 3b. Check recently created repos (potential dead drops)
info "Checking recently created repos in $ORG..."
RECENT_REPOS=$(gh api "/orgs/$ORG/repos?sort=created&direction=desc&per_page=10" \
    --jq '.[] | "\(.name) | created: \(.created_at)"' 2>/dev/null || true)
if [[ -n "$RECENT_REPOS" ]]; then
    warn "Recently created repos (review for unexpected entries):"
    echo "$RECENT_REPOS" | sed 's/^/    /'
fi

# 3c. Search for C2 domains in available logs
if [[ "$C2_DOMAINS" != "__C2_DOMAINS__" ]]; then
    info "C2 domain IOC check..."
    info "To search workflow logs for C2 indicators, download logs with:"
    for domain in $C2_DOMAINS; do
        info "  gh run view <RUN_ID> --log | grep -i '$domain'"
    done
fi

# 3d. Self-hosted runner persistence check (if running on a runner)
info "Checking for self-hosted runner persistence artifacts..."
PERSISTENCE_FOUND=false

for pp in ~/.config/sysmon/sysmon.py ~/.local/share/pgmon/service.py \
          ~/.config/systemd/user/pgmon.service /var/lib/svc_internal/runner.py \
          /etc/systemd/system/internal-monitor.service /var/lib/pgmon/pgmon.py; do
    if [[ -e "$pp" ]]; then
        finding "Persistence artifact found: $pp"
        PERSISTENCE_FOUND=true
    fi
done

if ! $PERSISTENCE_FOUND; then
    ok "No known persistence artifacts found on this host"
fi

# Check for suspicious systemd services
SUSPECT_SERVICES=$(find ~/.config/systemd/user/ -name "*.service" -mtime -7 2>/dev/null || true)
if [[ -n "$SUSPECT_SERVICES" ]]; then
    warn "Recent systemd user services (review manually):"
    echo "$SUSPECT_SERVICES" | sed 's/^/    /'
fi

# ======================== PHASE 4: CONTAINMENT ===============================

print_phase "4" "Containment"

if [[ ${#FINDINGS[@]} -eq 0 ]]; then
    ok "No findings — containment actions are optional"
    info "Consider pinning action references to SHAs as a precaution anyway"
fi

# 4a. Cancel in-flight runs (if affected repos identified)
if [[ -n "${AFFECTED_REPOS:-}" ]]; then
    while IFS= read -r repo; do
        IN_PROGRESS=$(gh api "/repos/$repo/actions/runs?status=in_progress" \
            --jq '.workflow_runs[].id' 2>/dev/null || true)
        if [[ -n "$IN_PROGRESS" ]]; then
            while IFS= read -r run_id; do
                confirm_action \
                    "Cancel in-progress run $run_id in $repo" \
                    "gh api -X POST '/repos/$repo/actions/runs/$run_id/cancel'" || true
            done <<< "$IN_PROGRESS"
        fi
    done <<< "$AFFECTED_REPOS"
fi

# 4b. Clear actions cache for affected repos
if [[ -n "${AFFECTED_REPOS:-}" ]]; then
    while IFS= read -r repo; do
        confirm_action \
            "Clear GitHub Actions cache for $repo" \
            "gh api -X DELETE '/repos/$repo/actions/caches'" || true
    done <<< "$AFFECTED_REPOS"
fi

# 4c. Pin to safe SHA
if [[ "$SAFE_SHA" != "__SAFE_SHA__" ]]; then
    info "Recommended: pin $COMPROMISED_ACTION to safe SHA in all workflow files:"
    info "  uses: $COMPROMISED_ACTION@$SAFE_SHA"
fi

# 4d. Remove persistence artifacts
if $PERSISTENCE_FOUND; then
    for pp in ~/.config/sysmon/sysmon.py ~/.local/share/pgmon/service.py \
              ~/.config/systemd/user/pgmon.service /var/lib/svc_internal/runner.py \
              /etc/systemd/system/internal-monitor.service /var/lib/pgmon/pgmon.py; do
        if [[ -e "$pp" ]]; then
            confirm_action \
                "Remove persistence artifact: $pp" \
                "rm -f '$pp'" || true
        fi
    done
fi

# ======================== PHASE 5: CREDENTIAL ROTATION =======================

print_phase "5" "Credential Rotation Checklist"

if [[ ${#FINDINGS[@]} -gt 0 ]]; then
    finding "Findings detected — credential rotation is strongly recommended"
    echo ""
    echo -e "  ${RED}${BOLD}Rotate ALL secrets accessible to affected workflows:${NC}"
else
    info "Review the following credential classes for rotation"
    echo ""
fi

# 5a. List repo-level secrets for affected repos
if [[ -n "${AFFECTED_REPOS:-}" ]]; then
    info "Listing secrets accessible to affected workflows..."
    while IFS= read -r repo; do
        echo ""
        echo -e "  ${BOLD}Repo: $repo${NC}"

        REPO_SECRETS=$(gh api "/repos/$repo/actions/secrets" --jq '.secrets[].name' 2>/dev/null || true)
        if [[ -n "$REPO_SECRETS" ]]; then
            warn "Repository secrets:"
            echo "$REPO_SECRETS" | sed 's/^/    /'
        fi

        ENVS=$(gh api "/repos/$repo/environments" --jq '.environments[].name' 2>/dev/null || true)
        if [[ -n "$ENVS" ]]; then
            while IFS= read -r env_name; do
                ENV_SECRETS=$(gh api "/repos/$repo/environments/$env_name/secrets" --jq '.secrets[].name' 2>/dev/null || true)
                if [[ -n "$ENV_SECRETS" ]]; then
                    warn "Environment '$env_name' secrets:"
                    echo "$ENV_SECRETS" | sed 's/^/    /'
                fi
            done <<< "$ENVS"
        fi
    done <<< "$AFFECTED_REPOS"
fi

# 5b. List org-level secrets
echo ""
info "Organization-level secrets:"
ORG_SECRETS=$(gh api "/orgs/$ORG/actions/secrets" --jq '.secrets[].name' 2>/dev/null || true)
if [[ -n "$ORG_SECRETS" ]]; then
    warn "Organization secrets (accessible to affected workflows):"
    echo "$ORG_SECRETS" | sed 's/^/    /'
else
    ok "No organization-level secrets found (or insufficient permissions to list)"
fi

echo ""
echo "  Credential rotation checklist:"
echo "  [ ] GITHUB_TOKEN — review permissions, revoke PATs, regenerate deploy keys"
echo "  [ ] Cloud credentials — AWS access keys, GCP service account keys, Azure client secrets"
echo "  [ ] Docker registry — Docker Hub, GHCR, ECR, GCR tokens"
echo "  [ ] Package registries — npm, PyPI, RubyGems, NuGet tokens"
echo "  [ ] SSH deploy keys"
echo "  [ ] Database credentials in CI secrets"
echo "  [ ] Webhook URLs (Slack, PagerDuty)"
echo "  [ ] Any other secrets listed above"
echo ""

# ======================== PHASE 6: PREVENTION ================================

print_phase "6" "Prevention Recommendations"

echo "  1. Pin ALL actions to full commit SHAs (never use @v1, @v2, @main):"
echo "     uses: $COMPROMISED_ACTION@$SAFE_SHA"
echo "  2. Enable Dependabot for GitHub Actions version updates"
echo "  3. Use GitHub Actions allow-list (Settings > Actions > General)"
echo "  4. Use StepSecurity Harden-Runner for egress monitoring"
echo "  5. Minimize GITHUB_TOKEN permissions (use 'permissions:' block)"
echo "  6. Separate CI and deploy secrets using GitHub Environments"
echo "  7. Use OIDC (OpenID Connect) instead of long-lived cloud credentials"
echo ""

# ======================== SUMMARY ============================================

print_header "Summary"

echo -e "${BOLD}Findings: ${#FINDINGS[@]}${NC}"
if [[ ${#FINDINGS[@]} -gt 0 ]]; then
    for f in "${FINDINGS[@]}"; do
        echo -e "  ${RED}*${NC} $f"
    done
else
    echo -e "  ${GREEN}No indicators of compromise found${NC}"
fi

echo ""
echo -e "${BOLD}Actions taken: ${#ACTIONS_TAKEN[@]}${NC}"
if [[ ${#ACTIONS_TAKEN[@]} -gt 0 ]]; then
    for a in "${ACTIONS_TAKEN[@]}"; do
        echo -e "  ${GREEN}*${NC} $a"
    done
fi

echo ""
if [[ ${#FINDINGS[@]} -gt 3 ]]; then
    echo -e "${RED}${BOLD}WARNING: Multiple indicators found. Credential rotation is mandatory.${NC}"
    echo -e "${RED}${BOLD}This script checks common indicators but cannot guarantee full detection.${NC}"
    echo -e "${RED}${BOLD}Consider the cascading impact — what other systems did the stolen CI credentials have access to?${NC}"
elif [[ ${#FINDINGS[@]} -gt 0 ]]; then
    echo -e "${YELLOW}Some indicators were found. Review them carefully and rotate credentials if in doubt.${NC}"
    echo -e "${YELLOW}Remember: compromised Trivy creds led to KICS, which led to LiteLLM. Check for cascading impact.${NC}"
else
    echo -e "${GREEN}No indicators found in the checks performed.${NC}"
    echo -e "${YELLOW}This does not guarantee safety — monitor advisories for updates.${NC}"
fi

echo ""
info "Report generated at $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
