#!/usr/bin/env bash
# =============================================================================
# PyPI Supply Chain Attack — Compromise Checker
# Generated by pypi-supply-chain-response skill
#
# Usage:
#   ./check_compromise.sh <package_name> [--dry-run]
#
# This script checks whether a compromised PyPI package is installed in your
# environment, hunts for indicators of compromise, and offers guided
# remediation with confirmation prompts before any destructive action.
#
# Customize the variables in the CONFIGURATION section below for your specific
# incident before running.
# =============================================================================

set -euo pipefail

# --------------- CONFIGURATION — EDIT THESE FOR YOUR INCIDENT ----------------

# Compromised versions (space-separated)
COMPROMISED_VERSIONS="${COMPROMISED_VERSIONS:-__COMPROMISED_VERSIONS__}"

# Last known safe version to pin to
SAFE_VERSION="${SAFE_VERSION:-__SAFE_VERSION__}"

# Attack window (UTC)
ATTACK_WINDOW_START="${ATTACK_WINDOW_START:-__WINDOW_START__}"
ATTACK_WINDOW_END="${ATTACK_WINDOW_END:-__WINDOW_END__}"

# Known C2 domains (space-separated, for log searching)
C2_DOMAINS="${C2_DOMAINS:-__C2_DOMAINS__}"

# Known persistence paths (space-separated)
PERSISTENCE_PATHS="${PERSISTENCE_PATHS:-__PERSISTENCE_PATHS__}"

# Known malicious filenames (space-separated, e.g., pth files)
MALICIOUS_FILES="${MALICIOUS_FILES:-__MALICIOUS_FILES__}"

# ----------------------------- END CONFIGURATION -----------------------------

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color
BOLD='\033[1m'

# Globals
PACKAGE="${1:-}"
DRY_RUN=false
FINDINGS=()
ACTIONS_TAKEN=()

for arg in "$@"; do
    if [[ "$arg" == "--dry-run" ]]; then
        DRY_RUN=true
    fi
done

# ----------------------------- UTILITY FUNCTIONS -----------------------------

print_header() {
    echo ""
    echo -e "${BOLD}${BLUE}═══════════════════════════════════════════════════════════${NC}"
    echo -e "${BOLD}${BLUE}  $1${NC}"
    echo -e "${BOLD}${BLUE}═══════════════════════════════════════════════════════════${NC}"
    echo ""
}

print_phase() {
    echo ""
    echo -e "${BOLD}── Phase $1: $2 ──${NC}"
    echo ""
}

ok()      { echo -e "  ${GREEN}[OK]${NC} $1"; }
finding() { echo -e "  ${RED}[!!]${NC} $1"; FINDINGS+=("$1"); }
warn()    { echo -e "  ${YELLOW}[??]${NC} $1"; }
info()    { echo -e "  ${BLUE}[--]${NC} $1"; }

confirm_action() {
    local description="$1"
    local command="$2"

    if $DRY_RUN; then
        info "DRY RUN — would execute: $command"
        return 1
    fi

    echo ""
    echo -e "  ${YELLOW}Action:${NC} $description"
    echo -e "  ${YELLOW}Command:${NC} $command"
    read -r -p "  Proceed? [y/N] " response
    case "$response" in
        [yY][eE][sS]|[yY])
            eval "$command"
            ACTIONS_TAKEN+=("$description")
            return 0
            ;;
        *)
            info "Skipped."
            return 1
            ;;
    esac
}

check_command() {
    command -v "$1" >/dev/null 2>&1
}

# ----------------------------- VALIDATION ------------------------------------

if [[ -z "$PACKAGE" ]] || [[ "$PACKAGE" == "--dry-run" ]]; then
    echo "Usage: $0 <package_name> [--dry-run]"
    echo ""
    echo "Example: $0 litellm"
    echo "         $0 litellm --dry-run"
    exit 1
fi

print_header "PyPI Supply Chain Attack Checker"
info "Package:              $PACKAGE"
info "Compromised versions: $COMPROMISED_VERSIONS"
info "Safe version:         $SAFE_VERSION"
info "Dry run:              $DRY_RUN"
echo ""

# ======================== PHASE 1: EXPOSURE CHECK ============================

print_phase "1" "Exposure Check"

# 1a. Check if package is installed
INSTALLED_VERSION=""
if check_command pip; then
    INSTALLED_VERSION=$(pip show "$PACKAGE" 2>/dev/null | grep "^Version:" | awk '{print $2}' || true)
    if [[ -n "$INSTALLED_VERSION" ]]; then
        finding "Package $PACKAGE is installed — version $INSTALLED_VERSION"
        INSTALL_LOCATION=$(pip show "$PACKAGE" 2>/dev/null | grep "^Location:" | awk '{print $2}' || true)
        info "Location: $INSTALL_LOCATION"
    else
        ok "Package $PACKAGE is not installed in the current pip environment"
    fi
else
    warn "pip not found — skipping pip check"
fi

# 1b. Check uv
if check_command uv; then
    UV_VERSION=$(uv pip show "$PACKAGE" 2>/dev/null | grep "^Version:" | awk '{print $2}' || true)
    if [[ -n "$UV_VERSION" ]]; then
        finding "Package $PACKAGE found via uv — version $UV_VERSION"
    else
        ok "Package $PACKAGE not found via uv"
    fi
fi

# 1c. Reverse dependency check
if check_command pipdeptree; then
    info "Checking reverse dependencies (what pulled $PACKAGE in)..."
    RDEPS=$(pipdeptree -r -p "$PACKAGE" 2>/dev/null || true)
    if [[ -n "$RDEPS" ]]; then
        warn "Reverse dependency chain:"
        echo "$RDEPS" | sed 's/^/    /'
    fi
else
    warn "pipdeptree not installed — cannot check transitive dependencies"
    info "Install with: pip install pipdeptree"
fi

# 1d. Hunt across all environments
info "Searching for $PACKAGE across all site-packages directories..."
FOUND_DIRS=$(find / -path "*/site-packages/$PACKAGE" -type d 2>/dev/null || true)
if [[ -n "$FOUND_DIRS" ]]; then
    finding "Found $PACKAGE in these locations:"
    echo "$FOUND_DIRS" | sed 's/^/    /'
else
    ok "No $PACKAGE directories found in site-packages across the system"
fi

# 1e. Check for malicious files (e.g., .pth files)
if [[ "$MALICIOUS_FILES" != "__MALICIOUS_FILES__" ]]; then
    for mfile in $MALICIOUS_FILES; do
        info "Searching for malicious file: $mfile"
        FOUND_MFILES=$(find / -name "$mfile" 2>/dev/null || true)
        if [[ -n "$FOUND_MFILES" ]]; then
            finding "Malicious file $mfile found:"
            echo "$FOUND_MFILES" | sed 's/^/    /'
        else
            ok "Malicious file $mfile not found"
        fi
    done
fi

# 1f. Check package manager caches
info "Checking package manager caches..."
CACHE_HITS=""
if [[ -d "$HOME/.cache/uv" ]]; then
    UV_CACHE=$(find "$HOME/.cache/uv" -name "*${PACKAGE}*" 2>/dev/null || true)
    if [[ -n "$UV_CACHE" ]]; then
        CACHE_HITS="$CACHE_HITS\n$UV_CACHE"
    fi
fi
if check_command pip; then
    PIP_CACHE=$(pip cache list "$PACKAGE" 2>/dev/null || true)
    if [[ -n "$PIP_CACHE" ]]; then
        CACHE_HITS="$CACHE_HITS\n$PIP_CACHE"
    fi
fi
if [[ -n "$CACHE_HITS" ]]; then
    warn "Package found in caches (could be reinstalled from cache):"
    echo -e "$CACHE_HITS" | sed 's/^/    /'
else
    ok "No cached copies found"
fi

# 1g. Check requirements files
info "Searching requirements and config files for $PACKAGE references..."
REQ_HITS=$(grep -rn "$PACKAGE" --include="*.txt" --include="*.toml" --include="*.lock" --include="*.cfg" --include="*.in" . 2>/dev/null || true)
if [[ -n "$REQ_HITS" ]]; then
    warn "Found $PACKAGE in project files:"
    echo "$REQ_HITS" | sed 's/^/    /'
    # Check for dangerous pinning
    UNPINNED=$(echo "$REQ_HITS" | grep -E "(>=|~=|>|${PACKAGE}[^=])" || true)
    if [[ -n "$UNPINNED" ]]; then
        finding "Loosely pinned or unpinned $PACKAGE references (vulnerable to pulling bad versions):"
        echo "$UNPINNED" | sed 's/^/    /'
    fi
fi

# ======================== PHASE 2: VERSION CONFIRMATION ======================

print_phase "2" "Version Confirmation"

IS_COMPROMISED=false
if [[ -n "$INSTALLED_VERSION" ]] && [[ "$COMPROMISED_VERSIONS" != "__COMPROMISED_VERSIONS__" ]]; then
    for cv in $COMPROMISED_VERSIONS; do
        if [[ "$INSTALLED_VERSION" == "$cv" ]]; then
            finding "COMPROMISED VERSION $cv IS INSTALLED"
            IS_COMPROMISED=true
        fi
    done
    if ! $IS_COMPROMISED; then
        ok "Installed version $INSTALLED_VERSION is not in the compromised versions list"
    fi
else
    if [[ -z "$INSTALLED_VERSION" ]]; then
        ok "Package not installed — version check not needed"
    else
        warn "No compromised versions configured — check manually"
    fi
fi

# Check for suspicious .pth files in site-packages
info "Scanning for suspicious .pth files..."
if check_command python; then
    SITE_DIR=$(python -c "import site; print(site.getsitepackages()[0])" 2>/dev/null || true)
    if [[ -n "$SITE_DIR" ]] && [[ -d "$SITE_DIR" ]]; then
        SUSPECT_PTH=$(find "$SITE_DIR" -name "*.pth" -exec grep -l "base64\|subprocess\|exec\|eval\|compile" {} \; 2>/dev/null || true)
        if [[ -n "$SUSPECT_PTH" ]]; then
            finding "Suspicious .pth files with code execution patterns:"
            echo "$SUSPECT_PTH" | sed 's/^/    /'
        else
            ok "No suspicious .pth files found"
        fi
    fi
fi

# ======================== PHASE 3: IOC HUNTING ===============================

print_phase "3" "IOC Hunting"

if $IS_COMPROMISED || [[ ${#FINDINGS[@]} -gt 2 ]]; then
    info "Indicators suggest possible compromise — running IOC checks..."
else
    info "Running IOC checks as a precaution..."
fi

# 3a. Filesystem persistence
info "Checking for persistence mechanisms..."
for ppath in ~/.config/systemd/user/*.service; do
    if [[ -f "$ppath" ]]; then
        PMOD=$(stat -c %Y "$ppath" 2>/dev/null || stat -f %m "$ppath" 2>/dev/null || echo "0")
        warn "systemd user service found: $ppath (modified: $(date -d @"$PMOD" 2>/dev/null || date -r "$PMOD" 2>/dev/null || echo 'unknown'))"
    fi
done

if [[ "$PERSISTENCE_PATHS" != "__PERSISTENCE_PATHS__" ]]; then
    for pp in $PERSISTENCE_PATHS; do
        pp_expanded=$(eval echo "$pp")
        if [[ -e "$pp_expanded" ]]; then
            finding "Known persistence artifact found: $pp_expanded"
        else
            ok "Persistence path clean: $pp_expanded"
        fi
    done
fi

SUSPICIOUS_PY=$(find ~/.config -name "*.py" -mtime -7 2>/dev/null || true)
if [[ -n "$SUSPICIOUS_PY" ]]; then
    warn "Recent Python files in ~/.config:"
    echo "$SUSPICIOUS_PY" | sed 's/^/    /'
fi

CRON_ENTRIES=$(crontab -l 2>/dev/null || true)
if [[ -n "$CRON_ENTRIES" ]]; then
    warn "Crontab entries (review manually):"
    echo "$CRON_ENTRIES" | sed 's/^/    /'
fi

# 3b. Network connections
info "Checking network connections from Python processes..."
PYTHON_CONNS=$(ss -tnp 2>/dev/null | grep python || true)
if [[ -n "$PYTHON_CONNS" ]]; then
    warn "Active network connections from Python:"
    echo "$PYTHON_CONNS" | sed 's/^/    /'
else
    ok "No active Python network connections"
fi

# 3c. C2 domain lookups
if [[ "$C2_DOMAINS" != "__C2_DOMAINS__" ]]; then
    info "Searching logs for known C2 domains..."
    for domain in $C2_DOMAINS; do
        LOG_HITS=$(grep -rF "$domain" /var/log/ 2>/dev/null | head -5 || true)
        if [[ -n "$LOG_HITS" ]]; then
            finding "C2 domain $domain found in logs:"
            echo "$LOG_HITS" | sed 's/^/    /'
        else
            ok "No log entries for $domain"
        fi
    done
fi

# 3d. Suspicious Python processes
info "Checking for orphaned Python processes..."
PYTHON_PROCS=$(ps aux | grep "[p]ython" | grep -v "check_compromise" || true)
if [[ -n "$PYTHON_PROCS" ]]; then
    warn "Running Python processes (review manually):"
    echo "$PYTHON_PROCS" | sed 's/^/    /'
fi

# 3e. Credential access timestamps
info "Checking recent access to credential files..."
for cred_path in ~/.ssh ~/.aws ~/.config/gcloud ~/.kube; do
    if [[ -d "$cred_path" ]]; then
        RECENT_ACCESS=$(find "$cred_path" -atime -1 2>/dev/null || true)
        if [[ -n "$RECENT_ACCESS" ]]; then
            warn "Recently accessed files in $cred_path:"
            echo "$RECENT_ACCESS" | sed 's/^/    /'
        fi
    fi
done

# 3f. Kubernetes checks (if kubectl is available)
if check_command kubectl; then
    info "Checking Kubernetes for lateral movement indicators..."
    RECENT_PODS=$(kubectl get pods -n kube-system --sort-by=.metadata.creationTimestamp 2>/dev/null | tail -5 || true)
    if [[ -n "$RECENT_PODS" ]]; then
        warn "Recent kube-system pods (review manually):"
        echo "$RECENT_PODS" | sed 's/^/    /'
    fi
fi

# ======================== PHASE 4: CONTAINMENT ===============================

print_phase "4" "Containment"

if [[ ${#FINDINGS[@]} -eq 0 ]]; then
    ok "No findings — containment actions are optional"
    info "Consider purging caches as a precaution anyway"
fi

# Uninstall compromised package
if [[ -n "$INSTALLED_VERSION" ]]; then
    confirm_action \
        "Uninstall $PACKAGE ($INSTALLED_VERSION)" \
        "pip uninstall $PACKAGE -y" || true
fi

# Purge caches
confirm_action \
    "Purge pip cache" \
    "pip cache purge" || true

if [[ -d "$HOME/.cache/uv" ]]; then
    confirm_action \
        "Purge uv cache" \
        "rm -rf $HOME/.cache/uv" || true
fi

# Remove persistence artifacts
if [[ "$PERSISTENCE_PATHS" != "__PERSISTENCE_PATHS__" ]]; then
    for pp in $PERSISTENCE_PATHS; do
        pp_expanded=$(eval echo "$pp")
        if [[ -e "$pp_expanded" ]]; then
            confirm_action \
                "Remove persistence artifact: $pp_expanded" \
                "rm -f '$pp_expanded'" || true
        fi
    done
fi

# Pin safe version
if [[ "$SAFE_VERSION" != "__SAFE_VERSION__" ]]; then
    info "Recommended: pin $PACKAGE==$SAFE_VERSION in your requirements files"
fi

# ======================== PHASE 5: CREDENTIAL ROTATION =======================

print_phase "5" "Credential Rotation Checklist"

if $IS_COMPROMISED; then
    finding "COMPROMISED VERSION WAS INSTALLED — credential rotation is mandatory"
    echo ""
    echo -e "  ${RED}${BOLD}Rotate ALL of the following:${NC}"
else
    info "Review the following credential classes for rotation"
    echo ""
fi

echo "  [ ] SSH keys          — ~/.ssh/id_*"
echo "  [ ] AWS credentials   — ~/.aws/credentials, access keys"
echo "  [ ] GCP credentials   — application default credentials, service account keys"
echo "  [ ] Azure tokens      — ~/.azure/"
echo "  [ ] Kubernetes        — ~/.kube/config"
echo "  [ ] .env files        — all API keys, secrets, tokens"
echo "  [ ] Git credentials   — ~/.git-credentials, PATs"
echo "  [ ] Database passwords"
echo "  [ ] CI/CD secrets     — GitHub Actions, GitLab CI variables"
echo "  [ ] Crypto wallets    — transfer funds to new wallets"
echo ""

# List .env files with sensitive keys
info "Scanning for .env files with credential keys..."
ENV_FILES=$(find . -name ".env*" -type f 2>/dev/null || true)
if [[ -n "$ENV_FILES" ]]; then
    warn ".env files found — these keys need rotation:"
    for ef in $ENV_FILES; do
        grep -h "KEY\|SECRET\|TOKEN\|PASSWORD\|CREDENTIAL" "$ef" 2>/dev/null | cut -d= -f1 | sort -u | sed 's/^/    /'
    done
fi

# ======================== PHASE 6: PREVENTION ================================

print_phase "6" "Prevention Recommendations"

echo "  1. Pin exact versions:  $PACKAGE==$SAFE_VERSION (not >= or ~=)"
echo "  2. Generate SBOMs:      cyclonedx-py requirements -i requirements.txt -o sbom.json"
echo "  3. Run pip-audit in CI: pip-audit --require-hashes"
echo "  4. Use uv --exclude-newer to freeze supply chain timeline"
echo "  5. Scope CI secrets to individual steps, not workflow-level env vars"
echo "  6. Use lockfiles with hashes: pip-compile --generate-hashes"
echo "  7. Consider Trusted Publishing (OIDC) for your own PyPI packages"
echo ""

# ======================== SUMMARY ============================================

print_header "Summary"

echo -e "${BOLD}Findings: ${#FINDINGS[@]}${NC}"
if [[ ${#FINDINGS[@]} -gt 0 ]]; then
    for f in "${FINDINGS[@]}"; do
        echo -e "  ${RED}*${NC} $f"
    done
else
    echo -e "  ${GREEN}No indicators of compromise found${NC}"
fi

echo ""
echo -e "${BOLD}Actions taken: ${#ACTIONS_TAKEN[@]}${NC}"
if [[ ${#ACTIONS_TAKEN[@]} -gt 0 ]]; then
    for a in "${ACTIONS_TAKEN[@]}"; do
        echo -e "  ${GREEN}*${NC} $a"
    done
fi

echo ""
if $IS_COMPROMISED; then
    echo -e "${RED}${BOLD}WARNING: Compromised version was installed. Credential rotation is mandatory.${NC}"
    echo -e "${RED}${BOLD}This script checks common indicators but cannot guarantee full detection.${NC}"
    echo -e "${RED}${BOLD}Monitor advisories and consider a full forensic investigation.${NC}"
elif [[ ${#FINDINGS[@]} -gt 0 ]]; then
    echo -e "${YELLOW}Some indicators were found. Review them carefully and rotate credentials if in doubt.${NC}"
else
    echo -e "${GREEN}No indicators found in the checks performed.${NC}"
    echo -e "${YELLOW}This does not guarantee safety — monitor advisories for updates.${NC}"
fi

echo ""
info "Report generated at $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
